import React,{useEffect,useMemo,useState} from 'react';
import {X,Activity,Scale,Calendar,ClipboardCheck,AlertTriangle,FileCheck,PackageCheck,ReceiptText} from 'lucide-react';
import {usePetGestor} from '../../context/AppContext';
import type {Pet,PetWeightRecord} from '../../types';
import {loadPetWeightHistory} from '../../services/petRecordRepository';

type TimelineItem={id:string;date:string;type:string;title:string;description:string;badge?:string};
export const PetRecordModal:React.FC<{pet:Pet|null;onClose:()=>void}>=({pet,onClose})=>{
 const {company,appointments,serviceOrders,petCheckins,petIncidents,termAcceptances,loyaltyPackages}=usePetGestor();
 const [weights,setWeights]=useState<PetWeightRecord[]>([]); const [loading,setLoading]=useState(false);
 useEffect(()=>{if(!pet)return;setLoading(true);loadPetWeightHistory(company.id,pet.id).then(setWeights).catch(()=>setWeights([])).finally(()=>setLoading(false))},[company.id,pet]);
 const items=useMemo(()=>{if(!pet)return[];const list:TimelineItem[]=[];
  appointments.filter(x=>x.pet_id===pet.id).forEach(x=>list.push({id:`a-${x.id}`,date:x.scheduled_at,type:'atendimento',title:`Atendimento: ${x.service_name||'Serviço'}`,description:`Status: ${x.status.replaceAll('_',' ')}${x.employee_name?` · Profissional: ${x.employee_name}`:''}`,badge:x.status}));
  serviceOrders.filter(x=>x.pet_id===pet.id).forEach(x=>list.push({id:`o-${x.id}`,date:x.created_at||'',type:'comanda',title:`Comanda #${x.order_number}`,description:x.items.map(i=>`${i.quantity}× ${i.name}`).join(', ')||'Sem itens',badge:x.status}));
  petCheckins.filter(x=>x.pet_id===pet.id).forEach(x=>list.push({id:`c-${x.id}`,date:x.checked_in_at,type:'checkin',title:`Check-in por ${x.responsible_name}`,description:[x.weight?`${x.weight} kg`:null,x.pre_existing_conditions,x.belongings?`Objetos: ${x.belongings}`:null].filter(Boolean).join(' · ')||'Entrada sem observações',badge:x.status}));
  petIncidents.filter(x=>x.pet_id===pet.id).forEach(x=>list.push({id:`i-${x.id}`,date:x.occurred_at,type:'incidente',title:`Incidente: ${x.incident_type}`,description:`${x.description}${x.actions_taken?` · Ação: ${x.actions_taken}`:''}`,badge:x.severity}));
  termAcceptances.filter(x=>x.pet_id===pet.id||(!x.pet_id&&x.customer_id===pet.customer_id)).forEach(x=>list.push({id:`t-${x.id}`,date:x.accepted_at,type:'termo',title:`Termo aceito: ${x.term_title}`,description:`Versão ${x.term_version} · Aceite por ${x.accepted_by_name}`,badge:'aceito'}));
  loyaltyPackages.filter(x=>x.pet_id===pet.id).forEach(x=>list.push({id:`p-${x.id}`,date:x.created_at||x.starts_at,type:'pacote',title:`Pacote: ${x.package_name}`,description:`${x.used_uses}/${x.total_uses} utilizações · Validade até ${new Date(x.expires_at).toLocaleDateString('pt-BR')}`,badge:x.status}));
  weights.forEach(x=>list.push({id:`w-${x.id}`,date:x.recorded_at,type:'peso',title:`Peso registrado: ${x.weight} kg`,description:x.notes||`Origem: ${x.source}`,badge:x.source}));
  return list.filter(x=>x.date).sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());
 },[pet,appointments,serviceOrders,petCheckins,petIncidents,termAcceptances,loyaltyPackages,weights]);
 if(!pet)return null; const incidents=petIncidents.filter(x=>x.pet_id===pet.id); const completed=appointments.filter(x=>x.pet_id===pet.id&&x.status==='entregue').length;
 const Icon=({type}:{type:string})=>type==='peso'?<Scale/>:type==='incidente'?<AlertTriangle/>:type==='termo'?<FileCheck/>:type==='pacote'?<PackageCheck/>:type==='comanda'?<ReceiptText/>:type==='checkin'?<ClipboardCheck/>:<Calendar/>;
 return <div className="fixed inset-0 z-50 bg-slate-950/60 backdrop-blur-sm p-3 sm:p-6 flex items-center justify-center"><div className="bg-slate-50 dark:bg-slate-950 w-full max-w-5xl max-h-[94vh] rounded-3xl overflow-hidden border dark:border-slate-800 shadow-2xl flex flex-col">
  <div className="p-5 bg-white dark:bg-slate-900 border-b dark:border-slate-800 flex justify-between gap-4"><div className="flex gap-3">{pet.photo_url?<img src={pet.photo_url} className="w-14 h-14 rounded-2xl object-cover"/>:<div className="w-14 h-14 rounded-2xl bg-teal-100 text-teal-700 grid place-items-center text-xl font-black">{pet.name[0]}</div>}<div><h2 className="text-xl font-bold flex items-center gap-2"><Activity className="w-5 text-teal-600"/>Prontuário de {pet.name}</h2><p className="text-xs text-slate-500">{pet.breed||pet.species} · Tutor: {pet.customer_name} · Peso atual: {pet.weight} kg</p></div></div><button onClick={onClose} className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800"><X/></button></div>
  <div className="p-4 sm:p-6 overflow-y-auto space-y-5"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[[completed,'Atendimentos'],[incidents.length,'Incidentes'],[weights.length,'Pesagens'],[loyaltyPackages.filter(x=>x.pet_id===pet.id&&x.status==='ativo').length,'Pacotes ativos']].map(([v,l])=><div key={String(l)} className="bg-white dark:bg-slate-900 border dark:border-slate-800 rounded-2xl p-4"><b className="text-xl text-teal-600">{v}</b><p className="text-[11px] text-slate-500">{l}</p></div>)}</div>
   {(pet.allergies||pet.diseases||pet.medications||pet.restrictions)&&<div className="rounded-2xl border border-rose-200 bg-rose-50 dark:bg-rose-950/30 dark:border-rose-900 p-4"><b className="text-rose-700 dark:text-rose-300">Alertas permanentes</b><p className="text-xs mt-1 text-rose-700 dark:text-rose-300">{[pet.allergies&&`Alergias: ${pet.allergies}`,pet.diseases&&`Doenças: ${pet.diseases}`,pet.medications&&`Medicamentos: ${pet.medications}`,pet.restrictions&&`Restrições: ${pet.restrictions}`].filter(Boolean).join(' · ')}</p></div>}
   <div><h3 className="font-bold mb-3">Linha do tempo completa</h3>{loading?<div className="p-8 text-center text-slate-400">Carregando prontuário...</div>:items.length===0?<div className="p-8 text-center text-slate-400 bg-white dark:bg-slate-900 rounded-2xl border">Nenhum evento registrado.</div>:<div className="space-y-3">{items.map(x=><div key={x.id} className="bg-white dark:bg-slate-900 border dark:border-slate-800 rounded-2xl p-4 flex gap-3"><div className={`w-9 h-9 rounded-xl grid place-items-center shrink-0 [&>svg]:w-4 ${x.type==='incidente'?'bg-rose-100 text-rose-600':'bg-teal-100 text-teal-700'}`}><Icon type={x.type}/></div><div className="flex-1 min-w-0"><div className="flex justify-between gap-3"><b className="text-sm">{x.title}</b><span className="text-[10px] uppercase text-slate-400">{x.badge}</span></div><p className="text-xs text-slate-500 mt-1">{x.description}</p><time className="text-[10px] text-slate-400">{new Date(x.date).toLocaleString('pt-BR')}</time></div></div>)}</div>}</div>
  </div></div></div>
}
