create table public.purchase_orders(
 id uuid primary key default gen_random_uuid(),order_number bigint generated always as identity,company_id uuid not null references public.companies(id),supplier_id uuid not null,
 status text not null default 'rascunho' check(status in('rascunho','enviado','recebido_parcial','recebido','cancelado')),expected_delivery_date date,due_date date not null,
 subtotal numeric(12,2) not null default 0,discount numeric(12,2) not null default 0,freight numeric(12,2) not null default 0,total_amount numeric(12,2) not null default 0,notes text,created_by uuid not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(id,company_id),constraint purchase_supplier_company_fkey foreign key(supplier_id,company_id) references public.suppliers(id,company_id),constraint purchase_creator_company_fkey foreign key(created_by,company_id) references public.profiles(id,company_id)
);
create table public.purchase_order_items(
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),purchase_order_id uuid not null,product_id uuid not null,product_name text not null,quantity numeric(12,3) not null check(quantity>0),received_quantity numeric(12,3) not null default 0 check(received_quantity>=0 and received_quantity<=quantity),unit_cost numeric(12,2) not null check(unit_cost>=0),total_cost numeric(12,2) not null check(total_cost>=0),batch_number text,expiration_date date,created_at timestamptz not null default now(),
 constraint purchase_item_order_company_fkey foreign key(purchase_order_id,company_id) references public.purchase_orders(id,company_id) on delete cascade,constraint purchase_item_product_company_fkey foreign key(product_id,company_id) references public.products(id,company_id)
);
alter table public.financial_transactions add column purchase_order_id uuid;
alter table public.financial_transactions add constraint financial_purchase_order_fkey foreign key(purchase_order_id,company_id) references public.purchase_orders(id,company_id);
create index purchase_orders_company_date_idx on public.purchase_orders(company_id,created_at desc);create index purchase_orders_supplier_idx on public.purchase_orders(supplier_id);create index purchase_orders_creator_idx on public.purchase_orders(created_by);
create index purchase_items_order_idx on public.purchase_order_items(purchase_order_id);create index purchase_items_product_idx on public.purchase_order_items(product_id);create index purchase_items_company_idx on public.purchase_order_items(company_id);
create index financial_purchase_order_idx on public.financial_transactions(purchase_order_id) where purchase_order_id is not null;
alter table public.purchase_orders enable row level security;alter table public.purchase_order_items enable row level security;
grant select,insert,update on public.purchase_orders,public.purchase_order_items to authenticated;revoke all on public.purchase_orders,public.purchase_order_items from anon;
create policy purchase_orders_select on public.purchase_orders for select to authenticated using((select private.is_company_member(company_id)));
create policy purchase_orders_write on public.purchase_orders for all to authenticated using((select private.has_company_role(company_id,array['proprietario','administrador','gerente','estoquista']))) with check((select private.has_company_role(company_id,array['proprietario','administrador','gerente','estoquista'])));
create policy purchase_items_select on public.purchase_order_items for select to authenticated using((select private.is_company_member(company_id)));
create policy purchase_items_write on public.purchase_order_items for all to authenticated using((select private.has_company_role(company_id,array['proprietario','administrador','gerente','estoquista']))) with check((select private.has_company_role(company_id,array['proprietario','administrador','gerente','estoquista'])));
create trigger purchase_orders_updated_at before update on public.purchase_orders for each row execute function private.set_updated_at();

create function public.create_purchase_order(p_supplier_id uuid,p_due_date date,p_expected_delivery_date date,p_items jsonb,p_discount numeric default 0,p_freight numeric default 0,p_notes text default null)
returns public.purchase_orders language plpgsql security invoker set search_path='' as $$
declare company uuid;actor uuid:=(select auth.uid());result public.purchase_orders;subtotal numeric;item jsonb;prod public.products;
begin select company_id into company from public.profiles where id=actor and is_active and role=any(array['proprietario','administrador','gerente','estoquista']);if company is null then raise exception 'Acesso negado';end if;
 if not exists(select 1 from public.suppliers where id=p_supplier_id and company_id=company and is_active) then raise exception 'Fornecedor inválido';end if;if jsonb_array_length(p_items)=0 then raise exception 'Adicione ao menos um produto';end if;
 select sum((x->>'quantity')::numeric*(x->>'unit_cost')::numeric) into subtotal from jsonb_array_elements(p_items)x;if subtotal-p_discount+p_freight<0 then raise exception 'Total inválido';end if;
 insert into public.purchase_orders(company_id,supplier_id,status,expected_delivery_date,due_date,subtotal,discount,freight,total_amount,notes,created_by)values(company,p_supplier_id,'enviado',p_expected_delivery_date,p_due_date,subtotal,p_discount,p_freight,subtotal-p_discount+p_freight,p_notes,actor)returning*into result;
 for item in select*from jsonb_array_elements(p_items) loop select*into prod from public.products where id=(item->>'product_id')::uuid and company_id=company;if not found then raise exception 'Produto inválido';end if;insert into public.purchase_order_items(company_id,purchase_order_id,product_id,product_name,quantity,unit_cost,total_cost,batch_number,expiration_date)values(company,result.id,prod.id,prod.name,(item->>'quantity')::numeric,(item->>'unit_cost')::numeric,(item->>'quantity')::numeric*(item->>'unit_cost')::numeric,item->>'batch_number',nullif(item->>'expiration_date','')::date);end loop;
 insert into public.financial_transactions(company_id,type,category,description,amount,due_date,status,supplier_id,purchase_order_id,created_by)values(company,'despesa','Compra de Mercadorias',format('Pedido de compra #%s',result.order_number),result.total_amount,p_due_date,'pendente',p_supplier_id,result.id,actor);return result;end$$;
revoke all on function public.create_purchase_order(uuid,date,date,jsonb,numeric,numeric,text) from public,anon;grant execute on function public.create_purchase_order(uuid,date,date,jsonb,numeric,numeric,text) to authenticated;

create function public.receive_purchase_order(p_order_id uuid,p_receipts jsonb)returns public.purchase_orders language plpgsql security invoker set search_path='' as $$
declare company uuid;actor uuid:=(select auth.uid());ord public.purchase_orders;entry jsonb;it public.purchase_order_items;prod public.products;qty numeric;newstock numeric;newcost numeric;
begin select company_id into company from public.profiles where id=actor and is_active and role=any(array['proprietario','administrador','gerente','estoquista']);if company is null then raise exception 'Acesso negado';end if;select*into ord from public.purchase_orders where id=p_order_id and company_id=company for update;if not found or ord.status in('recebido','cancelado')then raise exception 'Pedido indisponível para recebimento';end if;
 for entry in select*from jsonb_array_elements(p_receipts)loop qty:=(entry->>'quantity')::numeric;select*into it from public.purchase_order_items where id=(entry->>'item_id')::uuid and purchase_order_id=ord.id for update;if not found or qty<=0 or it.received_quantity+qty>it.quantity then raise exception 'Quantidade de recebimento inválida';end if;select*into prod from public.products where id=it.product_id for update;newstock:=prod.current_stock+qty;newcost:=case when newstock=0 then it.unit_cost else ((prod.current_stock*prod.cost_price)+(qty*it.unit_cost))/newstock end;update public.products set current_stock=newstock,cost_price=round(newcost,2),supplier_id=ord.supplier_id where id=prod.id;update public.purchase_order_items set received_quantity=received_quantity+qty,batch_number=coalesce(nullif(entry->>'batch_number',''),batch_number),expiration_date=coalesce(nullif(entry->>'expiration_date','')::date,expiration_date)where id=it.id;insert into public.stock_movements(company_id,product_id,movement_type,quantity,unit_cost,batch_number,expiration_date,reason,previous_stock,new_stock,created_by)values(company,prod.id,'compra',qty,it.unit_cost,coalesce(nullif(entry->>'batch_number',''),it.batch_number),coalesce(nullif(entry->>'expiration_date','')::date,it.expiration_date),format('Recebimento do pedido #%s',ord.order_number),prod.current_stock,newstock,actor);end loop;
 update public.purchase_orders set status=case when exists(select 1 from public.purchase_order_items where purchase_order_id=ord.id and received_quantity<quantity)then'recebido_parcial'else'recebido'end where id=ord.id returning*into ord;return ord;end$$;
revoke all on function public.receive_purchase_order(uuid,jsonb) from public,anon;grant execute on function public.receive_purchase_order(uuid,jsonb) to authenticated;
create trigger audit_purchase_orders after insert or update or delete on public.purchase_orders for each row execute function private.capture_audit_log();create trigger audit_purchase_order_items after insert or update or delete on public.purchase_order_items for each row execute function private.capture_audit_log();
