begin;
create table public.notification_preferences(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),user_id uuid not null,appointments boolean not null default true,low_stock boolean not null default true,expirations boolean not null default true,financial boolean not null default true,updated_at timestamptz not null default now(),unique(user_id,company_id),constraint notification_preferences_user_company_fkey foreign key(user_id,company_id) references public.profiles(id,company_id));
create table public.notifications(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),user_id uuid not null,type text not null check(type in('agendamento','estoque','validade','financeiro')),severity text not null default 'info' check(severity in('info','aviso','critico')),title text not null,message text not null,source_key text not null,is_read boolean not null default false,read_at timestamptz,created_at timestamptz not null default now(),unique(user_id,source_key),constraint notifications_user_company_fkey foreign key(user_id,company_id) references public.profiles(id,company_id));
create index notifications_user_unread_idx on public.notifications(user_id,created_at desc) where not is_read;create index notifications_company_idx on public.notifications(company_id);create index notification_preferences_company_idx on public.notification_preferences(company_id);
alter table public.notification_preferences enable row level security;alter table public.notifications enable row level security;
create policy notification_preferences_select on public.notification_preferences for select to authenticated using(user_id=(select auth.uid()) and (select private.is_company_member(company_id)));
create policy notification_preferences_insert on public.notification_preferences for insert to authenticated with check(user_id=(select auth.uid()) and (select private.is_company_member(company_id)));
create policy notification_preferences_update on public.notification_preferences for update to authenticated using(user_id=(select auth.uid()) and (select private.is_company_member(company_id))) with check(user_id=(select auth.uid()) and (select private.is_company_member(company_id)));
create policy notifications_select on public.notifications for select to authenticated using(user_id=(select auth.uid()) and (select private.is_company_member(company_id)));
create policy notifications_insert on public.notifications for insert to authenticated with check(user_id=(select auth.uid()) and (select private.is_company_member(company_id)));
create policy notifications_update on public.notifications for update to authenticated using(user_id=(select auth.uid()) and (select private.is_company_member(company_id))) with check(user_id=(select auth.uid()) and (select private.is_company_member(company_id)));
create policy notifications_delete on public.notifications for delete to authenticated using(user_id=(select auth.uid()) and (select private.is_company_member(company_id)));
revoke all on public.notification_preferences,public.notifications from public,anon,authenticated;grant select,insert,update on public.notification_preferences to authenticated;grant select,insert,update,delete on public.notifications to authenticated;
create or replace function public.refresh_user_notifications() returns integer language plpgsql security invoker set search_path='' as $$
declare v_user uuid:=(select auth.uid());v_company uuid;v_role text;v_pref public.notification_preferences;v_count integer;
begin
 select company_id,role into v_company,v_role from public.profiles where id=v_user and is_active;if v_company is null then raise exception 'Acesso negado';end if;
 insert into public.notification_preferences(company_id,user_id)values(v_company,v_user)on conflict(user_id,company_id)do nothing;select*into v_pref from public.notification_preferences where user_id=v_user and company_id=v_company;
 if v_pref.appointments then insert into public.notifications(company_id,user_id,type,severity,title,message,source_key)
 select v_company,v_user,'agendamento','info','Agendamento próximo',format('%s · %s',coalesce(c.full_name,'Cliente'),to_char(a.scheduled_at,'DD/MM HH24:MI')),format('appointment:%s:%s',a.id,current_date) from public.appointments a left join public.customers c on c.id=a.customer_id and c.company_id=a.company_id where a.company_id=v_company and a.scheduled_at between now() and now()+interval'24 hours' and a.status not in('cancelado','concluido') on conflict(user_id,source_key)do nothing;end if;
 if v_pref.low_stock then insert into public.notifications(company_id,user_id,type,severity,title,message,source_key)
 select v_company,v_user,'estoque',case when p.current_stock=0 then'critico'else'aviso'end,'Estoque baixo',format('%s: %s %s (mínimo %s)',p.name,p.current_stock,p.unit,p.min_stock),format('stock:%s:%s',p.id,current_date) from public.products p where p.company_id=v_company and p.is_active and p.current_stock<=p.min_stock on conflict(user_id,source_key)do nothing;end if;
 if v_pref.expirations then insert into public.notifications(company_id,user_id,type,severity,title,message,source_key)
 select v_company,v_user,'validade',case when p.next_expiration_date<current_date then'critico'else'aviso'end,case when p.next_expiration_date<current_date then'Produto vencido'else'Validade próxima'end,format('%s · lote %s · %s',p.name,coalesce(p.next_batch_number,'não informado'),to_char(p.next_expiration_date,'DD/MM/YYYY')),format('expiry:%s:%s:%s',p.id,p.next_expiration_date,current_date) from public.products p where p.company_id=v_company and p.is_active and p.next_expiration_date<=current_date+60 on conflict(user_id,source_key)do nothing;end if;
 if v_pref.financial and v_role=any(array['proprietario','administrador','gerente']) then insert into public.notifications(company_id,user_id,type,severity,title,message,source_key)
 select v_company,v_user,'financeiro',case when f.due_date<current_date then'critico'else'aviso'end,case when f.due_date<current_date then'Conta vencida'else'Conta próxima do prazo'end,format('%s · R$ %s · %s',f.description,to_char(f.amount,'FM999G999G990D00'),to_char(f.due_date,'DD/MM/YYYY')),format('financial:%s:%s',f.id,current_date) from public.financial_transactions f where f.company_id=v_company and f.status in('pendente','atrasado') and f.due_date<=current_date+7 on conflict(user_id,source_key)do nothing;end if;
 select count(*) into v_count from public.notifications where user_id=v_user and not is_read;return v_count;
end$$;
revoke all on function public.refresh_user_notifications() from public,anon;grant execute on function public.refresh_user_notifications() to authenticated;
create trigger audit_notification_preferences after insert or update or delete on public.notification_preferences for each row execute function private.capture_audit_log();
commit;
